### PR TITLE
fixed right prompt right justification being off by a single cell

### PR DESCRIPTION
**Pull request by leath-dub**
I noticed that the right prompt doesn't fully justify to the right ( it is off by one cell ), this was a simple fix, hopefully I am not missing anything - it works fine with my prompt

### CODE REVIEW

**Comment by magicant** [comment]
Thanks for the patch❤️, but I'm afraid I hesitate to apply it as the one-column gap is actually intentional.
When printing the right prompt, the cursor moves after the prompt. If there is no room for the cursor to fit in, the terminal may place it out of the screen or in the next line, which is not desired. All terminal implementations I have tested seem to keep the cursor on the last column of the last line, but I'm not sure if this is a guaranteed behavior in all existing implementations. So, I don't think it is safe to trim the gap.

**Comment by magicant** [comment]
If you really favor the right prompt printed without the gap, it would be safer to add a shell option to remove the gap rather than unconditionally trim it.

**Comment by leath-dub** [comment]
I see, which ever works, could you point me to where you set shell options ?

ps: im also happy to update manpage

**Comment by leath-dub** [comment]
ok I have got the option working now, just need to update the documentation, ill keep you posted :).

> I am really unsure how the documentation works, I can see it is marking up to the webpage. Just don't know how many files need editing

**Comment by leath-dub** [comment]
ok just updated the docs now, hope I have not made a silly mistake. The project is actually very easy to work on btw, it builds easily and the structure is pretty intuitive ( especially with grep xd )

> I just realised that my lsp has made some edits to po/ja.po, this is probably of note, maybe we can ignore the file.

EDIT: I restored the ja.po file, I apologise for the messy commits

**Comment by magicant** [comment]
Great thanks! And could you update test cases as well? There are three test cases that contain an expected list of options:

- https://github.com/magicant/yash/blob/a069af213c4593387609a04e5045a25703339893/tests/help-y.tst#L790
- https://github.com/magicant/yash/blob/a069af213c4593387609a04e5045a25703339893/tests/startup-y.tst#L568
- https://github.com/magicant/yash/blob/a069af213c4593387609a04e5045a25703339893/tests/startup-y.tst#L626

You can run the tests by `make check`.

**Comment by leath-dub** [comment]
ok just added the tests there, here was the result of ``make check``
test

**Comment by magicant** [comment]
Great, I'm going to merge this

**Comment by leath-dub** [comment]
great !, I have to thank you for your tremendous work on this project, I use it daily and its brilliant.

**Comment by magicant** [comment]
The upstream svn server seems to have trouble committing the patch. I'll try later.

**Comment by magicant** [comment]
Merged 32d19e852fc59b1abf6da36afd65c20788904d17. Thanks!

**Comment by leath-dub** [comment]
nice ! this is one of my first OSS contributions

**Pull request closed without merging**
